# Generated by Django 5.0.6 on 2024-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('instrument_type', models.CharField(choices=[('saxophone', 'Saxophone'), ('cello', 'Cello'), ('clarinet', 'Clarinet'), ('harp', 'Harp'), ('bass', 'Bass'), ('guitar', 'Guitar'), ('trombone', 'Trombone')], max_length=50)),
            ],
        ),
    ]
