# Generated by Django 5.0.6 on 2024-07-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_albums_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
