# Generated by Django 5.0.6 on 2024-07-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_alter_musicians_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
