# Generated by Django 5.0.6 on 2024-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_albums_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='albums',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
