# Generated by Django 5.0.6 on 2024-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_albums_album_release_date_alter_albums_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
