# Generated by Django 5.0.6 on 2024-07-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_alter_musicians_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
