# Generated by Django 5.0.6 on 2024-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='instrument_type',
            field=models.CharField(choices=[('saxophone', 'Saxophone'), ('cello', 'Cello'), ('clarinet', 'Clarinet'), ('harp', 'Harp'), ('bass', 'Bass'), ('guitar', 'Guitar'), ('trombone', 'Trombone')], max_length=50),
        ),
    ]
