# Generated by Django 5.0.6 on 2024-07-02 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
