# Generated by Django 5.0.6 on 2024-06-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('profiles', '0002_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author',
            field=models.OneToOneField(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
    ]
